/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package calculator;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2022-4-11")
public class DivideByZeroException extends TException implements org.apache.thrift.TBase<DivideByZeroException, DivideByZeroException._Fields>, java.io.Serializable, Cloneable, Comparable<DivideByZeroException> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DivideByZeroException");

  private static final org.apache.thrift.protocol.TField MESSAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("message", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField N1_FIELD_DESC = new org.apache.thrift.protocol.TField("n1", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField N2_FIELD_DESC = new org.apache.thrift.protocol.TField("n2", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new DivideByZeroExceptionStandardSchemeFactory());
    schemes.put(TupleScheme.class, new DivideByZeroExceptionTupleSchemeFactory());
  }

  public String message; // required
  public int n1; // required
  public int n2; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MESSAGE((short)1, "message"),
    N1((short)2, "n1"),
    N2((short)3, "n2");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MESSAGE
          return MESSAGE;
        case 2: // N1
          return N1;
        case 3: // N2
          return N2;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __N1_ISSET_ID = 0;
  private static final int __N2_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MESSAGE, new org.apache.thrift.meta_data.FieldMetaData("message", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.N1, new org.apache.thrift.meta_data.FieldMetaData("n1", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.N2, new org.apache.thrift.meta_data.FieldMetaData("n2", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DivideByZeroException.class, metaDataMap);
  }

  public DivideByZeroException() {
  }

  public DivideByZeroException(
    String message,
    int n1,
    int n2)
  {
    this();
    this.message = message;
    this.n1 = n1;
    setN1IsSet(true);
    this.n2 = n2;
    setN2IsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DivideByZeroException(DivideByZeroException other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetMessage()) {
      this.message = other.message;
    }
    this.n1 = other.n1;
    this.n2 = other.n2;
  }

  public DivideByZeroException deepCopy() {
    return new DivideByZeroException(this);
  }

  @Override
  public void clear() {
    this.message = null;
    setN1IsSet(false);
    this.n1 = 0;
    setN2IsSet(false);
    this.n2 = 0;
  }

  public String getMessage() {
    return this.message;
  }

  public DivideByZeroException setMessage(String message) {
    this.message = message;
    return this;
  }

  public void unsetMessage() {
    this.message = null;
  }

  /** Returns true if field message is set (has been assigned a value) and false otherwise */
  public boolean isSetMessage() {
    return this.message != null;
  }

  public void setMessageIsSet(boolean value) {
    if (!value) {
      this.message = null;
    }
  }

  public int getN1() {
    return this.n1;
  }

  public DivideByZeroException setN1(int n1) {
    this.n1 = n1;
    setN1IsSet(true);
    return this;
  }

  public void unsetN1() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __N1_ISSET_ID);
  }

  /** Returns true if field n1 is set (has been assigned a value) and false otherwise */
  public boolean isSetN1() {
    return EncodingUtils.testBit(__isset_bitfield, __N1_ISSET_ID);
  }

  public void setN1IsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __N1_ISSET_ID, value);
  }

  public int getN2() {
    return this.n2;
  }

  public DivideByZeroException setN2(int n2) {
    this.n2 = n2;
    setN2IsSet(true);
    return this;
  }

  public void unsetN2() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __N2_ISSET_ID);
  }

  /** Returns true if field n2 is set (has been assigned a value) and false otherwise */
  public boolean isSetN2() {
    return EncodingUtils.testBit(__isset_bitfield, __N2_ISSET_ID);
  }

  public void setN2IsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __N2_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case MESSAGE:
      if (value == null) {
        unsetMessage();
      } else {
        setMessage((String)value);
      }
      break;

    case N1:
      if (value == null) {
        unsetN1();
      } else {
        setN1((Integer)value);
      }
      break;

    case N2:
      if (value == null) {
        unsetN2();
      } else {
        setN2((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case MESSAGE:
      return getMessage();

    case N1:
      return Integer.valueOf(getN1());

    case N2:
      return Integer.valueOf(getN2());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case MESSAGE:
      return isSetMessage();
    case N1:
      return isSetN1();
    case N2:
      return isSetN2();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof DivideByZeroException)
      return this.equals((DivideByZeroException)that);
    return false;
  }

  public boolean equals(DivideByZeroException that) {
    if (that == null)
      return false;

    boolean this_present_message = true && this.isSetMessage();
    boolean that_present_message = true && that.isSetMessage();
    if (this_present_message || that_present_message) {
      if (!(this_present_message && that_present_message))
        return false;
      if (!this.message.equals(that.message))
        return false;
    }

    boolean this_present_n1 = true;
    boolean that_present_n1 = true;
    if (this_present_n1 || that_present_n1) {
      if (!(this_present_n1 && that_present_n1))
        return false;
      if (this.n1 != that.n1)
        return false;
    }

    boolean this_present_n2 = true;
    boolean that_present_n2 = true;
    if (this_present_n2 || that_present_n2) {
      if (!(this_present_n2 && that_present_n2))
        return false;
      if (this.n2 != that.n2)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_message = true && (isSetMessage());
    list.add(present_message);
    if (present_message)
      list.add(message);

    boolean present_n1 = true;
    list.add(present_n1);
    if (present_n1)
      list.add(n1);

    boolean present_n2 = true;
    list.add(present_n2);
    if (present_n2)
      list.add(n2);

    return list.hashCode();
  }

  @Override
  public int compareTo(DivideByZeroException other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetMessage()).compareTo(other.isSetMessage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMessage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.message, other.message);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetN1()).compareTo(other.isSetN1());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetN1()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.n1, other.n1);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetN2()).compareTo(other.isSetN2());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetN2()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.n2, other.n2);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("DivideByZeroException(");
    boolean first = true;

    sb.append("message:");
    if (this.message == null) {
      sb.append("null");
    } else {
      sb.append(this.message);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("n1:");
    sb.append(this.n1);
    first = false;
    if (!first) sb.append(", ");
    sb.append("n2:");
    sb.append(this.n2);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DivideByZeroExceptionStandardSchemeFactory implements SchemeFactory {
    public DivideByZeroExceptionStandardScheme getScheme() {
      return new DivideByZeroExceptionStandardScheme();
    }
  }

  private static class DivideByZeroExceptionStandardScheme extends StandardScheme<DivideByZeroException> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DivideByZeroException struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MESSAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.message = iprot.readString();
              struct.setMessageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // N1
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.n1 = iprot.readI32();
              struct.setN1IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // N2
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.n2 = iprot.readI32();
              struct.setN2IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DivideByZeroException struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.message != null) {
        oprot.writeFieldBegin(MESSAGE_FIELD_DESC);
        oprot.writeString(struct.message);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(N1_FIELD_DESC);
      oprot.writeI32(struct.n1);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(N2_FIELD_DESC);
      oprot.writeI32(struct.n2);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DivideByZeroExceptionTupleSchemeFactory implements SchemeFactory {
    public DivideByZeroExceptionTupleScheme getScheme() {
      return new DivideByZeroExceptionTupleScheme();
    }
  }

  private static class DivideByZeroExceptionTupleScheme extends TupleScheme<DivideByZeroException> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DivideByZeroException struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetMessage()) {
        optionals.set(0);
      }
      if (struct.isSetN1()) {
        optionals.set(1);
      }
      if (struct.isSetN2()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetMessage()) {
        oprot.writeString(struct.message);
      }
      if (struct.isSetN1()) {
        oprot.writeI32(struct.n1);
      }
      if (struct.isSetN2()) {
        oprot.writeI32(struct.n2);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DivideByZeroException struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.message = iprot.readString();
        struct.setMessageIsSet(true);
      }
      if (incoming.get(1)) {
        struct.n1 = iprot.readI32();
        struct.setN1IsSet(true);
      }
      if (incoming.get(2)) {
        struct.n2 = iprot.readI32();
        struct.setN2IsSet(true);
      }
    }
  }

}

